SAP/openui5-fhir

src/sap/fhir/model/r4/FHIRModel.js, test/localService/ResponseOfMultiplePutInBundle.json, test/qunit/model/FHIRModel.unit.js
When location header is of following "/Patient/3ac58844-5c7e-4b4f-8600-c0b836bfa48a/_history/f52ecc0d-16ef-4f5a-9183-9306f103685b"  the getBindingInfo fails throwing an error from model since extra / is getting appended.
TODO: Have a normalised function a central place to do this
=> fix: in case the location header has slash at the beginning

src/sap/fhir/model/r4/FHIRModel.js, src/sap/fhir/model/r4/lib/FHIRRequestor.js, test/qunit/model/FHIRModel.integration.js, test/qunit/model/FHIRModel.unit.js, test/qunit/model/FHIRTreeBinding.integration.js, test/sap-fhir-test-app/webapp/manifest.json, tsconfig.json
The default query parameters to be passed on resource type specific requests and not resource instance specific request (e.g /Patient?_total:accurate&_format:json). It should be of type key:value pairs. e.g. {'_total':'accurate'} -> http://hl7.org/fhir/http.html#parameters
=> fix: set the default query params based on configuration

docs/tutorials/2 Bindings.md
The binding syntax in a XMLView has to contain '{' and '}'.
=> docs(tutorial.Bindings): correct binding syntax

src/sap/fhir/model/r4/FHIRModel.js, test/qunit/model/FHIRModel.unit.js
hasResourceTypePendingChanges depends on the mChangedResources which gets updated even when the server data and the client data is the same.
=> fix: handling changed resources when the server state and the client state is the same

src/sap/fhir/model/r4/lib/FHIRRequestor.js, src/sap/fhir/model/r4/lib/RequestHandle.js, test/qunit/model/FHIRModel.unit.js, test/sap-fhir-test-app/webapp/controller/structureDefinition/StructureDefinition.controller.js
For intentional aborted requests dont trigger fireRequestFailed/fireRequestCompleted Event
https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/model/odata/ODataModel.js#L869
=> fix: dont trigger request failed for aborted requests

src/sap/fhir/model/r4/FHIRModel.js, test/localService/ValueSetSearchResponse.json, test/qunit/model/FHIRModel.unit.js
When ValueSet requests are made without the expand option the model doesn't map the response causing console logs.
=> fix: ValueSet calls without expand option

src/sap/fhir/model/r4/FHIRModel.js, test/qunit/model/FHIRModel.unit.js
During the second time or any number of times when the reset changes (edit scenario of same resource) is invoked , oDataServerState is not reinitialized properly causing inconsistencies  (actual server state data is lost)
=> fix: forceful update of server state variable in handleClient changes for multiple reset changes scenario

src/sap/fhir/model/r4/FHIRListBinding.js, src/sap/fhir/model/r4/FHIRTreeBinding.js, src/sap/fhir/model/r4/FHIRUtils.js, test/qunit/model/FHIRModel.unit.js
According to ui5 ListBinding the initial application filters/sorters can be a single or an array https://openui5.hana.ondemand.com/api/sap.ui.model.ListBinding
aFilters? sap.ui.model.Filter|sap.ui.model.Filter[] Predefined filter/s (can be either a filter or an array of filters)
So if a single filter object is given instead of array it doesnt get applied since the model expects an array as default. This fix ensures to convert single instance of filter to an array of filters before applying it to the corresponding binding. oData ListBinding also handles it in the same way
=> fix: single filter or sorter object

docs/tutorials/3 Advanced Bindings.md, package.json, src/sap/fhir/model/r4/FHIRFilterComplexOperator.js, src/sap/fhir/model/r4/FHIRFilterOperator.js, src/sap/fhir/model/r4/FHIRFilterOperatorUtils.js, src/sap/fhir/model/r4/FHIRModel.js, src/sap/fhir/model/r4/FHIRUtils.js, test/qunit/model/FHIRFilterOperatorUtils.unit.js, test/qunit/model/FHIRModel.unit.js, test/qunit/unit.js
This PR contains the implementation for the support of _filter (https://www.hl7.org/fhir/search_filter.html)
_filter is an advanced search mechanism
Using the simpleFiltering value during the initialisation of model determines whether the request would be using _filter or regular search 
If the FilterType is of string then the filter value would be encoded with "" 
Using the bAnd key of Ui5 filter the logical connection value is determined to be `and` or `or`
Some of the examples on how the _filter value is generated
**To get the patients whose names are either Habibi or Damon**
`name eq "Habibi" or name eq "Damon"`
**To get the male patients whose names are either Habibi or Damon**
`gender eq male and (name eq "Habibi" or name eq "Damon")`
=> feat: Implement the support for _filter

docs/tutorials/4 Request Handling.md, src/sap/fhir/model/r4/FHIRListBinding.js, src/sap/fhir/model/r4/FHIRModel.js, src/sap/fhir/model/r4/lib/FHIRRequestor.js, src/sap/fhir/model/r4/lib/FHIRUrl.js, test/qunit/model/FHIRModel.unit.js, test/qunit/model/FHIRUrl.unit.js
This PR enables the support for RESTful search via POST
FHIR Specification : https://www.hl7.org/fhir/http.html#search
To enable secure search the model is initialised as follows
`var mParameters = {
search:{secure:true}
}`
If secure search is enabled in model then the search requests would be converted as follows
`/Patient?_count=json`
`/Patient/_search`
The request body will be x-www-form-urlencoded
Only interactions which match the following pattern would be transformed
`GET` `[base]/[type]{?[parameters]{&_format=[mime-type]}}`
Some examples which doesn't get transformed
`Patient/123`
`Patient/123/$look-up`
`Patient/123/history/2`
`ValueSet/$expand`
Enhancements done to FHIRUrl.js to determine whether the url is of type resource level search
In List binding in case of next link with …
=> feat: Implement RESTful Search Via POST

src/sap/fhir/model/r4/FHIRModel.js, test/qunit/model/FHIRModel.integration.js
This PR contains the fix  for sending  batch or transaction requests via sendPostRequestMethod of the fhir model and ensures proper parsing of response.
In case one of the requests in a bundle is a search call then the bundle response will have one entry which is of type bundle.  
**Sample Request**
`{"id":"7ff09ab5-6af1-4349-bb19-7fccfd62850d","type":"batch","resourceType":"Bundle","entry":[{"request":{"method":"GET","url":"Patient/a2522"}},{"request":{"method":"GET","url":"Coverage"}}]}`
**Response**
`{"resourceType":"Bundle","id":"f12caf0b-ce6d-4606-85d1-17ee5729a5ca","type":"batch-response","entry":[{"resource":{"resourceType":"Patient"},"response":{"status":"200 OK"}},{"resource":{"resourceType":"Bundle","id":"f57cc024-2d6c-4df2-aa3f-2ecf0e3d9c6c","meta":{"lastUpdated":"2021-04-22T19: …
=> fix: send batch/transaction requests 

src/sap/fhir/model/r4/FHIRUtils.js, test/qunit/model/FHIRModel.unit.js
Operator concatenation wasnot happening at root level when array of filters wherein each filter is again another chain
Model was forming filter like this without the logical connection for chained filters 
`_filter=( ( DRG eq "I47C" or DRG eq "test" )( patientLastName eq "esk" or patientLastName eq "we" ) )`
=> fix: operator concatenation in _filter

src/sap/fhir/model/r4/FHIRListBinding.js, test/qunit/model/FHIRModel.unit.js
Earlier the next links where getting triggered by default to fetch the next data. However if the service url is relative and the next links were complete url then the binding contexts is throwing error. The aim of the pr is to ensure no matter what the next links are transformed into the resource path and sent accordingly
=> fix: pagination calls when the service url is relative

src/sap/fhir/model/r4/FHIRListBinding.js, src/sap/fhir/model/r4/FHIRTreeBinding.js, src/sap/fhir/model/r4/FHIRUtils.js, test/qunit/model/FHIRModel.unit.js
initialise the combined filters property  by using the ui5 FilterProcessor.combineFilter to get the combined filter. this will merge filters  with bAnd property to be true. Similar to oData implementation https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/model/odata/ODataListBinding.js#L856
This property is necessary for mdc based filters to work as expected
https://github.com/SAP/openui5/blob/master/src/sap.ui.mdc/src/sap/ui/mdc/field/FieldValueHelpTableWrapperBase.js#L517
List Binding getFilterInfo Default Implemantation
https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/model/ListBinding.js#L428
=> fix: support combined filters 

src/sap/fhir/model/r4/FHIRFilterOperatorUtils.js, test/qunit/model/FHIRModel.unit.js
In case of mdc controls the filter object is generated by ui5 and hence the `valuetype` for string is not available to determine if it needs to be enclosed in quotes. 
The purpose of this PR is
1. to  identify string type based on js types and enclose it in quotes. if a valid date is given in string it wont be enclosed. 
2. to remove the conversion to iso string as if the type of the resource is not date time this would lead to incorrect filter results. For.eg. birthDate is of type date. 
This is a short term solution to handle dates and timezones(application will have the responsiblity to send it appropriately). 
Both of these are shorterm solutions
The long term solution is to determine the type of a search parameter based on the metadata
The long term solution of having Fhir date types …
=> fix: complex filter query

src/sap/fhir/model/r4/FHIRFilterOperatorUtils.js, test/qunit/model/FHIRModel.unit.js
when a string contains whitespace with numbers the date object validation is giving a proper date instance leading to miss of encoding the strings in quote. This pr would fix that by validating against regex mentioned in fhir  before encoding it in quotes
https://www.hl7.org/fhir/datatypes.html#string
=> fix: better handling of strings with ws and numbers

scripts/build/replaceCopyright.js
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
=> chore: change safeload to load

.github/workflows/ci.yml, src/sap/fhir/model/r4/FHIRListBinding.js, src/sap/fhir/model/r4/FHIRModel.js, test/data/Practitioner.json, test/qunit/model/FHIRModel.integration.js, test/qunit/model/FHIRModel.unit.js
This PR is for fixing the list binding still showing the removed items if submit changes is not done immediately.
Use another array to capture the client removed resources and fill it appropriately to decide whether during reset changes the contexts needs to be recreated (for those resources which are not yet submitted but was removed using the remove operation)
=> fix(sap.fhir.model.r4.FHIRListBinding): Trigger binding updates when resource is removed or a rollback is performed

package.json, src/sap/fhir/model/r4/FHIRListBinding.js, test/qunit/model/FHIRListBinding.integration.js
As per suggestion Server-side bindings (e.g. ODataListBinding) are expected to start with a "refresh" eventListBindings "initialize" , fire refresh-event (although not defined in the metadata)
=> fix(sap.fhir.model.r4.FHIRListBinding): Invalidate list bindings

.github/workflows/ci-pr.yml, .github/workflows/ci.yml
The  release is failing due to node version from semantic plugin
https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
Changing the version to 20.
=> chore: upgrade node version in workflows

src/sap/fhir/model/r4/lib/FHIRRequestor.js, test/qunit/model/FHIRModel.unit.js
FHIR Specification doesn't say _format can be added to delete calls. FHIR Model adds it by default
The delete interaction removes an existing resource. The interaction is performed by an HTTP DELETE command as shown:
```
DELETE [base]/[type]/[id]
```
The request body SHALL be empty.
https://www.hl7.org/fhir/http.html#delete
=> fix: avoid adding _format to delete calls

src/sap/fhir/model/r4/FHIRListBinding.js, src/sap/fhir/model/r4/FHIRModel.js, test/qunit/model/FHIRModel.integration.js, test/qunit/model/FHIRModel.unit.js
When secure search is enabled and the list binding is created with group id the resources post response is not mapped to the group id due to which the submit changes are not triggered for all those created contexts
=> fix: (sap.fhir.model.r4.FHIRListBinding) with secure search and group id
